### ISSUE TITLE
moc_mpris.sh exits successfully, but the MPRIS bridge does not seem to be working

### ISSUE THREAD

**Issue by brendenhoffman** [progwolff/moc-mpris#7]
I am not sure how to get it to start, I have also restarted moc. Running moc_mpris.sh in the terminal results in:
```
['-i']
None@None
```
systemctl status reports the script exited with status 0. There could potentially be an issue with the python script. I installed via AUR and had to install python-gobject as well. I only assume it is working because the script is no longer giving an error.

**Comment by progwolff** [comment]
What's the output of `systemctl status --user mocp_mpris.service`?

What's the output of `/usr/lib/moc-mpris/moc_mpris.sh`? (stop the service before running this command)

**Comment by elig0n** [comment]
@progwolff I have the same issue so I will share mine:

```
 $ systemctl status --user moc_mpris.service
 ● moc_mpris.service - Music on Console MPRIS bridge
      Loaded: loaded (/usr/lib/systemd/user/moc_mpris.service; enabled; preset: enabled)
      Active: activating (auto-restart) since Thu 2024-03-14 00:31:30 IST; 7s ago
     Process: 2311148 ExecStart=/usr/lib/moc-mpris/moc_mpris.sh (code=exited, status=0/SUCCESS)
    Main PID: 2311148 (code=exited, status=0/SUCCESS)
         CPU: 108ms
```

```
$ /usr/lib/moc-mpris/moc_mpris.sh      
['-i']
None@None    
```

Using `pudb` reveals this AttributeError:

```
*** Pudb UI Exception Encountered: stringifier failed ***                                                        
Traceback (most recent call last):                                                                               
  File "/usr/lib/python3.11/site-packages/pudb/var_view.py", line 607, in walk_value                             
    displayed_value = get_stringifier(iinfo)(value)                                                              
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 791, in __repr__                                
    if (self._object_path is not _MANY                                                                           
        ^^^^^^^^^^^^^^^^^                                                                                        
AttributeError: 'Mocp' object has no attribute '_object_path'                                                                                                                                  
```
